name: Run Terraform Tests

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  run-terraform-tests:
    name: Run Terraform Tests
    runs-on: ubuntu-latest

    steps:
      - name: Clone the Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd   #v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Test
        run: terraform test